// React_Case-Study/src/Components/CreateTaskComponent.js
import React, { Component } from "react";
import TaskService from "../TaskService";
import Home from './HomeComponent';

class CreateTaskComponent extends Component{
    constructor(props){
        super(props)
    this.state ={
        taskId:'',
        ownerId:'',
        creatorId:'',
        taskname:'',
        status:'',
        description:'',
        priority:'',
        notes:'',
        modifiedon:'',
        isBookmark:'',
        creatoron:''
  }
  this.changeHandler = this.changeHandler.bind(this);
  this.submitHandler=this.submitHandler.bind(this);
}
changeHandler(e){
    this.setState({[e.target.name]:e.target.value})
}
submitHandler(e){
    e.preventDefault()
    console.log(this.state)
    TaskService.createTask(this.state).then(response => {
        console.log(response)
    })
    .catch(error =>{
       console.log(error)
   })

   
}

render(){
    const{taskId,ownerId,creatorId,taskname,status,description,priority,notes,modifiedOn,isBookmark,creatorOn} = this.state
    return(
        <div style={{textAlign:"center"}}>
            <Home></Home>
            <h2>Create Task</h2>
            <form onSubmit={this.submitHandler}>
                <div>
                    TaskID:
                    <input type="number"
                    name="taskId"
                    value={taskId}
                    onChange={this.changeHandler}
                    />
                </div>
                <div>
                    Owner ID:
                    <input type="number"
                    name="ownerId"
                    value={ownerId}
                    onChange={this.changeHandler}
                    />
                </div>

                <div>
                    Creator ID:
                    <input type="number"
                    name="creatorId"
                    value={creatorId}
                    onChange={this.changeHandler}
                    />
                    </div>
                    <div>
                    Task name:
                    <input type="text"
                    name="taskname"
                    value={taskname}
                    onChange={this.changeHandler}
                    />
                    </div>
                    <div>
                    Status:
                    <input type="text"
                    name="status"
                    value={status}
                    onChange={this.changeHandler}
                    />
                    </div>

                    <div>
                    Description:
                    <input type="text"
                    name="description"
                    value={description}
                    onChange={this.changeHandler}
                    />
                    </div>

                    <div>
                    priority:
                    <input type="number"
                    name="priority"
                    value={priority}
                    onChange={this.changeHandler}
                    />
                    </div>
                    <div>
                    Notes:
                    <input type="text"
                    name="notes"
                    value={notes}
                    onChange={this.changeHandler}
                    />
                    </div>
                    <div>
                    isBookmark:
                    <input type="text"
                    name="isBookmark"
                    value={isBookmark}
                    onChange={this.changeHandler}
                    />
                    
                    </div>

                    <div>
                    CreatedOn:
                    <input type="date"
                    name="creatorOn"
                    value={creatorOn}
                    onChange={this.changeHandler}
                    />
                    </div>

                    <div>
                    modifiedOn:
                    <input type="date"
                    name="modifiedOn"
                    value={modifiedOn}
                    onChange={this.changeHandler}
                    />
                    </div>


                    
                <button type="submit">Submit</button>
               
            </form>
        </div>
    )

}
}
export default CreateTaskComponent

// Angular_Case-study/src/app/createtask/createtask.component.ts
import { Component, OnInit } from '@angular/core';
import { Task } from '../Task'; 
import { TaskService } from '../TaskService';
import {Router} from '@angular/router';

@Component({
  selector: 'app-createtask',
  templateUrl: './createtask.component.html',
  styleUrls: ['./createtask.component.css']
})
export class CreatetaskComponent implements OnInit {

  task: Task = new Task();
  submitted=false;
  

  constructor(private troService:TaskService,private router:Router) { }

  ngOnInit() {
  }

  newProduct():void{
    this.submitted = false;
    this.task = new Task();
  }

  createtask(){
    this.troService.createTask(this.task)
    .subscribe((data: any)=>console.log(data),(error: any)=>console.log(error));
    this.task=new Task();
    this.gotoList();
  }

  onSubmit(){
    this.submitted=true;
    this.createtask();
  }

  gotoList(){
    this.router.navigate(['/tasks'])
  }

}

<p>createtask works!</p>
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <ul>
    <li class="nav-item">
      <a routerLink="/tasks" class="btn btn-success mx-2" routerLinkActive="active">Back To Task-List</a>
  </li>
  </ul>
</nav>
<header class="header">
    <h4>CreateTask</h4>
    </header>
    <div [hidden]="submitted" style="width: 400px;">
        <form (ngSubmit)="onSubmit()">
          <div class="form-group">
            <label for="name">TaskID</label>
            <input type ="text" class ="form-control" id="taskId" required [(ngModel)]="task.taskId" name="taskId" >
          </div>
        
          <div class="form-group">
            <label for="name">OwnerID</label>
            <input type="text" class="form-control" id="ownerId" required [(ngModel)]="task.ownerId" name="ownerId">
          </div>
    
           <div class="form-group">
            <label for="name">CreatorID</label>
            <input type="text" class="form-control" id="creatorId" required [(ngModel)]="task.creatorId" name="creatorId">
          </div> 
    
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="taskname" required [(ngModel)]="task.taskname" name="taskname">
          </div>
    
    
          <div class="form-group">
            <label for="name">Description</label>
            <input type="text" class="form-control" id="description" required [(ngModel)]="task.description" name="description">
          </div>
    
    
          <div class="form-group">
            <label for="name">Status</label>
            <input type="text" class="form-control" id="status" required [(ngModel)]="task.status" name="status">
          </div>
    
    
          <div class="form-group">
            <label for="name">Priority</label>
            <input type="text" class="form-control" id="priority" required [(ngModel)]="task.priority" name="priority">
          </div>
    
    
          <div class="form-group">
            <label for="name">Notes</label>
            <input type="text" class="form-control" id="notes" required [(ngModel)]="task.notes" name="notes">
          </div>
    
          <div class="form-group">
            <label for="name">IsBookmark</label>
            <input type="text" class="form-control" id="isBookmark" required [(ngModel)]="task.isBookmark" name="isBookmark">
          </div>
    
          <div class="form-group">
            <label for="name">Created_On</label>
            <input type="date" class="form-control" id="creatorOn" required [(ngModel)]="task.creatorOn" name="creatorOn">
          </div>
    
          <div class="form-group">
            <label for="name">ModifiedOn</label>
            <input type="date" class="form-control" id="modifiedOn" required [(ngModel)]="task.modifiedOn" name="modifiedOn">
          </div>
          
    
          
    
          <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div>
    
    <div [hidden]="!submitted">
        <h4>You submitted successfully!</h4>
        <!-- <button class="btn btn-success" (click)="newEmployee()">Add</button> -->
      </div>
